version: '3.7'

# 컴퓨터들
services:
  # 컴퓨터 이름
  my-backend:
    build:
      # 파일 경로
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    ports:
      - 4000:4000
    env_file:
      - ./.env.docker

  # 컴퓨터 이름
  my-database:
    # platform: linux/x86_64
    image: mysql:latest
    environment:
      # 이건 도커안에 있는 mysql 파일 이름
      MYSQL_DATABASE: 'mydocker'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
